### ISSUE TITLE
Add project tracking

### ISSUE THREAD

**Issue by GabrielSousa02** [GabrielSousa02/helpout#13]
Epic: #9 

### Description

As a user I would like to track projects and basic information from the project, such as:
- Organization managing the project
- Estimated budget
- Estimated deadline
- Contact person for the project

### Tasks

- [ ] Create the project model
- [ ] Link to the organization model
- [ ] Create project CRUD interface
