### ISSUE TITLE
Create CRUD Frontend

### ISSUE THREAD

**Issue by GabrielSousa02** [GabrielSousa02/helpout#4]
Story: #2

### Description

We need an intuitive interface to submit new volunteers/organizations and see the ones on the database.

### Tasks

- [x] Create page to display all volunteers on a list
- [x] Create page to display all orgs on a list
- [x] Create page to submit new volunteers/orgs
- [x] Create page to see the detailed information and edit a volunteer/org
- [x] Create delete page for volunteers/orgs
